force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BTC</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TradeControllerTest.cls
@IsTest
public class TradeControllerTest {
    
	@IsTest(SeeAllData=true)
    static void newTrade(){
        CollaborationGroup newGroup=new CollaborationGroup(Name='TestTradeReviewers',CollaborationType='Private');
        insert newGroup;
        
        API_Key__mdt[] apiKeysMdt=[SELECT Value__c FROM API_Key__mdt WHERE DeveloperName='FixerIO'];
        System.assertEquals(1,apiKeysMdt.size(),'API Key record found');
        
        String fixerResponse='{"success":true,"timestamp":1598537646,"base":"EUR","date":"2020-08-27","rates":{"USD":1.1037,"EUR":1}}';
        
        MockHttpResponseHandler.SimpleMockResponse fixerCall = new MockHttpResponseHandler.SimpleMockResponse('GET', fixerResponse);
        fixerCall.statusCode=200;
        
        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        mock.addResponse('callout:FixerIO/latest?access_key='+apiKeysMdt[0].Value__c, fixerCall);
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        Datetime now=Datetime.now();
        Trade__c trade=TradeController.saveTrade(1000, 'EUR','USD');
        Test.stopTest();
        
        System.assertNotEquals(null, trade.Id, 'Trade saved to DB');
        
        trade=[SELECT Buy_Amount__c,Buy_Currency__c,Date_Booked__c,Name,Rate__c,Sell_Amount__c,Sell_Currency__c FROM Trade__c WHERE Id = :trade.Id];
        System.assertEquals(true, trade.Name.startsWith('TR'), 'Right id');
        System.assertEquals(1000*1.1037, trade.Buy_Amount__c, 'Right buy amount');
        System.assertEquals('USD', trade.Buy_Currency__c, 'Right buy currency code');
        System.assertEquals(1000, trade.Sell_Amount__c, 'Right buy amount');
        System.assertEquals('EUR', trade.Sell_Currency__c, 'Right buy currency code');
        System.assertEquals(1.1037, trade.Rate__c, 'Right buy amount');
        System.assertEquals(
            true,
            now.addSeconds(-4)<trade.Date_Booked__c
            &&
            trade.Date_Booked__c<now.addSeconds(4),
            'Right date booked'
        );
    }
    @IsTest
    static void newTradeException(){
        API_Key__mdt[] apiKeysMdt=[SELECT Value__c FROM API_Key__mdt WHERE DeveloperName='FixerIO'];
        System.assertEquals(1,apiKeysMdt.size(),'API Key record found');
        
        String fixerResponse='{"success":true,"timestamp":1598537646,"base":"EUR","date":"2020-08-27","rates":{"USD":1.1037,"EUR":1}}';
        
        MockHttpResponseHandler.SimpleMockResponse fixerCall = new MockHttpResponseHandler.SimpleMockResponse('GET', fixerResponse);
        fixerCall.statusCode=200;
        
        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        mock.addResponse('callout:FixerIO/latest?access_key='+apiKeysMdt[0].Value__c, fixerCall);
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        Exception ex;
        try{
            Trade__c trade=TradeController.saveTrade(1000, 'USD',null);
        }
        catch(AuraHandledException e){
            ex=e;
        }
        Test.stopTest();
        System.assertNotEquals(null, ex, 'Exception captured and handled');
    }
    
    @IsTest
    static void checkRates(){
        API_Key__mdt[] apiKeysMdt=[SELECT Value__c FROM API_Key__mdt WHERE DeveloperName='FixerIO'];
        System.assertEquals(1,apiKeysMdt.size(),'API Key record found');
        
        String fixerResponse='{"success":true,"timestamp":1598537646,"base":"EUR","date":"2020-08-27","rates":{"USD":1.1037,"EUR":1}}';
        
        MockHttpResponseHandler.SimpleMockResponse fixerCall = new MockHttpResponseHandler.SimpleMockResponse('GET', fixerResponse);
        fixerCall.statusCode=200;
        
        MockHttpResponseHandler mock = new MockHttpResponseHandler();
        mock.addResponse('callout:FixerIO/latest?access_key='+apiKeysMdt[0].Value__c, fixerCall);
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        Datetime now=Datetime.now();
        Double res=TradeController.conversionRate('EUR','USD');
        Test.stopTest();
        System.assertEquals(1.1037,res,'Right rate retrieved');
    }
    
    @IsTest
    static void queryTrades(){
        Test.startTest();
        Trade__c[] trades=TradeController.getTradeRecords();
        Test.stopTest();
        System.assertEquals(0, trades.size(),'Right amount of trade records found');
    }
}